### PR TITLE
Add support for protocol v5

### LINKED ISSUE #23: Add support for protocol V5
I'm opening this just so that we don't forget it :-)

The current V5 implementation is now completely obsolete, we need to remove what we have currently and re-implement V5 as it is now defined. Unfortunately, this will have to be done from scratch.

### PR DESCRIPTION
**Pull request by adutra**
Opening as a draft for now to gather feedback. Everything is working already and the `client` package supports sending and receiving segments. If you want to test against a real C* 4.0, simply run the `TestRemoteServerNoAuth` test (these tests are not executed automatically because they require a remote database to be available).

I designed the `segment` package to be completely independent from the `frame` package and vice versa. From inside the `segment` package, the payload is just an opaque byte slice.

The struct `frame.Frame` remains the main entry point into the library, regardless of whether segments are being used or not. In contrast, a `segment.Segment` is really a low-level struct mostly devoted to compression and checksumming, and I think it doesn't deserve to be exposed to the user. However, the decision to send a frame or a segment is to be taken by the higher layer above this library and requires to keep track of the connection state; this is exactly what `client.Client` does.

Things that could be added later: a write coalescer to `client.Client`.

cc @joao-r-reis @rchernobelskiy @mpenick 

fixes #23

### CODE REVIEW

**Comment by rchernobelskiy** [comment]
👍

**Comment by joao-r-reis** [comment]
I took a look at the overall structure and looks good. I noticed that you spent a considerable amount of time on the `client` package, are we still advertising it as recommended for non production usage only?

It would be great if we could have a common data type to represent a frame/segment and delegate the responsibility of switching between the two structures to that type but that could be added as an improvement. It's not clear right now what that data type would look like so we would definitely need a decent amount of time to come up with an easy to use API.

It's obvious that this PR introduces breaking changes but we never released this library technically so until we have a proper versioned release, users should expect breaking changes.

**Review by joao-r-reis — APPROVED** [review]
I took a look at the overall structure and looks good. I noticed that you spent a considerable amount of time on the client package, are we still advertising it as recommended for non production usage only?

It would be great if we could have a common data type to represent a frame/segment and delegate the responsibility of switching between the two structures to that type but that could be added as an improvement. It's not clear right now what that data type would look like so we would definitely need a decent amount of time to come up with an easy to use API.

It's obvious that this PR introduces breaking changes but we never released this library technically so until we have a proper versioned release, users should expect breaking changes.

**Comment by joao-r-reis** [comment]
justfyi, I merged #26 so that users can handle scenarios where requests are in the new v5 format (out of beta) gracefully. The error that was being thrown made it very hard for users to detect that an unsupported protocol version was being used.

Until this PR is merged, users can handle the new error type and attempt to downgrade the protocol version.

**Comment by adutra** [comment]
Thanks for the reviews @rchernobelskiy and @joao-r-reis ! And sorry for the delay in replying, I was OOO the last 2 weeks.

> I noticed that you spent a considerable amount of time on the client package, are we still advertising it as recommended for non production usage only?

We still don't have any benchmarks nor performance tests under heavy load for the client package... Until then, I don't feel comfortable recommending this for production use.

> It would be great if we could have a common data type to represent a frame/segment and delegate the responsibility of switching between the two structures to that type but that could be added as an improvement. It's not clear right now what that data type would look like (would this type be notified by the caller that a structure change needs to happen?) so we would definitely need a decent amount of time to come up with an easy to use API.

What you suggest is basically what the client package does. And yes, it is a bit disappointing that this logic is not in the production-ready packages, but I don't see any easy way to solve this. In the Java driver too, the logic to switch between both structures is in the driver-core module, not in the native-protocol module (in the `com.datastax.oss.driver.internal.core.channel` package). One of the reasons for that is because the "switching" requires a stateful component that keeps track of the connection state (pre- or post-handshake).

And yes, I agree we could keep investigating how to "push down" that logic from the client package to another one as a follow-up task.

**Comment by adutra** [comment]
> justfyi, I merged #26 so that users can handle scenarios where requests are in the new v5 format (out of beta) gracefully. The error that was being thrown made it very hard for users to detect that an unsupported protocol version was being used.
> 
> Until this PR is merged and we have proper V5 support, users can handle the new error type and attempt to downgrade the protocol version.

Thanks for the heads up, I rebased and force-pushed (no conflicts). I also fixed the CI failures (due to missing license headers).

**Pull request merged**
